# Generated by Django 2.0.7 on 2018-07-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
