# Generated by Django 2.0.7 on 2018-08-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autonomo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('telefone_fixo', models.IntegerField(blank=True, null=True, verbose_name='Telefone')),
                ('telefone_celular', models.IntegerField(verbose_name='Celular')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('cep', models.IntegerField(verbose_name='Cep')),
                ('cidade', models.CharField(max_length=150, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=150, verbose_name='Estado')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('link_social', models.CharField(blank=True, max_length=120, null=True, verbose_name='Social')),
            ],
        ),
    ]
