# Generated by Django 2.0.7 on 2018-07-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonomo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autonomo',
            name='email',
            field=models.EmailField(max_length=120, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='autonomo',
            name='link_social',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Social'),
        ),
        migrations.AlterField(
            model_name='autonomo',
            name='telefone_fixo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefone'),
        ),
    ]
