# Generated by Django 2.0.7 on 2018-07-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonomo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autonomo',
            name='email',
            field=models.EmailField(max_length=120, verbose_name='Email'),
        ),
    ]
