# Generated by Django 2.0.7 on 2018-07-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonomo', '0002_auto_20180723_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autonomo',
            name='link_social',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Social'),
        ),
        migrations.AlterField(
            model_name='autonomo',
            name='telefone_fixo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefone'),
        ),
    ]
